import Foundation
import CryptoKit

/// Handles the TOFU pairing handshake with a Windows AirBridge host.
final class PairingService {

    private let keychainStore: KeychainStore

    init(keychainStore: KeychainStore) {
        self.keychainStore = keychainStore
    }

    // MARK: - PIN generation

    /// Returns a 6-digit PIN string (zero-padded if necessary).
    func generatePin() -> String {
        let value = Int.random(in: 0..<1_000_000)
        return String(format: "%06d", value)
    }

    // MARK: - Pairing flow

    /// Executes the full pairing exchange over an established channel.
    ///
    /// Must be called before `channel.startReceiving()` — reads directly
    /// from the wire via `channel.receiveOne()`.
    ///
    /// - Parameters:
    ///   - channel: Connected, handshaked AirBridgeChannel.
    ///   - deviceId: The remote device's stable UUID from the HANDSHAKE.
    ///   - pin: The PIN to embed in the request (generated by caller and shown in UI).
    /// - Returns: `true` if pairing was accepted; `false` otherwise.
    func requestPairing(channel: AirBridgeChannel,
                        deviceId: String,
                        pin: String) async throws -> Bool {
        let privateKey = try keychainStore.getOrCreatePrivateKey()
        let publicKey = privateKey.publicKey.rawRepresentation

        // Build PAIRING_REQUEST payload (no type byte — ProtocolMessage carries the type).
        let requestBody = PairingRequestPayload(publicKey: publicKey, pin: pin)
        let payloadData = requestBody.toPayload()

        let message = ProtocolMessage(type: .pairingRequest, payload: payloadData)
        try await channel.send(message)

        // Wait for PAIRING_RESPONSE using direct receive (pre-loop phase).
        while true {
            let incoming = try await channel.receiveOne()
            guard incoming.type == .pairingResponse else { continue }

            let response = try PairingResponsePayload.fromPayload(incoming.payload)
            if response.accepted {
                try keychainStore.storePeerKey(response.publicKey, for: deviceId)
            }
            return response.accepted
        }
    }
}
